import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://www.selltousahome.com';

  const pages = [
    { url: `${baseUrl}`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/harrisburg-pa`, priority: 1.0, changeFrequency: 'monthly' as const },
    // Erie PA
    { url: `${baseUrl}/markets/erie-pa`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/erie-pa/market-report`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/erie-pa/inherited-property`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/erie-pa/foreclosure`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/erie-pa/divorce-sale`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/erie-pa/probate`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/erie-pa/tenant-occupied`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/erie-pa/code-violations`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/erie-pa/fire-damage`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/erie-pa/property-liens`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/erie-pa/faq`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/erie-pa/neighborhoods`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/sell-house-fast-harrisburg-pa-2026`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/harrisburg-pa/divorce-sale`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/harrisburg-pa/tenant-occupied`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/behind-on-payments`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/harrisburg-pa/inherited-property`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/harrisburg-pa/probate`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/harrisburg-pa/foreclosure`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/harrisburg-pa/code-violations`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/harrisburg-pa/property-liens`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/harrisburg-pa/fire-damage`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/harrisburg-pa/market-report`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/allentown-pa`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/allentown-pa/foreclosure`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/allentown-pa/probate`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/allentown-pa/inherited-property`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/allentown-pa/divorce-sale`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/allentown-pa/tenant-occupied`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/allentown-pa/code-violations`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/allentown-pa/market-report`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/sell-house-fast-allentown-pa-2026`, priority: 1.0, changeFrequency: 'monthly' as const },
    // King of Prussia PA
    { url: `${baseUrl}/markets/king-of-prussia-pa`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/sell-house-fast-king-of-prussia-pa-2026`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/king-of-prussia-pa/market-report`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/king-of-prussia-pa/inherited-property`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/king-of-prussia-pa/foreclosure`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/king-of-prussia-pa/divorce-sale`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/king-of-prussia-pa/probate`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/king-of-prussia-pa/tenant-occupied`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/king-of-prussia-pa/code-violations`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/king-of-prussia-pa/fire-damage`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/harrisburg-pa/neighborhoods`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/harrisburg-pa/faq`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/sell-as-is`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/back-taxes`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/foreclosure`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/vacant-property`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/relocation`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/inherited-property`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/divorce-sale`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/tenant-occupied`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/hoarding-property`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/selling-parents-house-nursing-home`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/probate`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/resources/how-much-do-cash-buyers-pay`, priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/resources/are-cash-home-buyers-legit`, priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/resources/cash-offer-vs-listing`, priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/resources/how-the-process-works`, priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/resources/sell-house-without-repairs`, priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/resources/how-fast-can-i-sell-for-cash`, priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/compare/usa-home-buyers-vs-opendoor`, priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/compare/usa-home-buyers-vs-homevestors`, priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/compare/usa-home-buyers-vs-listing-with-agent`, priority: 0.7, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/about`, priority: 0.6, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/reviews`, priority: 0.6, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/contact`, priority: 0.6, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/brand-facts`, priority: 0.5, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/press`, priority: 0.5, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/privacy-policy`, priority: 0.3, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/terms-of-service`, priority: 0.3, changeFrequency: 'monthly' as const },
    // Blog
    // Bethlehem PA
    { url: `${baseUrl}/markets/bethlehem-pa`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bethlehem-pa/market-report`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bethlehem-pa/inherited-property`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bethlehem-pa/foreclosure`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bethlehem-pa/divorce-sale`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bethlehem-pa/probate`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bethlehem-pa/tenant-occupied`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bethlehem-pa/code-violations`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bethlehem-pa/fire-damage`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bethlehem-pa/faq`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bethlehem-pa/neighborhoods`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/sell-house-fast-bethlehem-pa-2026`, priority: 1.0, changeFrequency: 'monthly' as const },
    // Lancaster PA
    { url: `${baseUrl}/markets/lancaster-pa`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/lancaster-pa/market-report`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/lancaster-pa/inherited-property`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/lancaster-pa/foreclosure`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/lancaster-pa/divorce-sale`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/lancaster-pa/probate`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/lancaster-pa/tenant-occupied`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/lancaster-pa/code-violations`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/lancaster-pa/fire-damage`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/lancaster-pa/faq`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/lancaster-pa/neighborhoods`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/sell-house-fast-lancaster-pa-2026`, priority: 1.0, changeFrequency: 'monthly' as const },
    // York PA
    { url: `${baseUrl}/markets/york-pa`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/york-pa/market-report`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/york-pa/inherited-property`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/york-pa/foreclosure`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/york-pa/divorce-sale`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/york-pa/probate`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/york-pa/tenant-occupied`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/york-pa/code-violations`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/york-pa/fire-damage`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/york-pa/faq`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/york-pa/neighborhoods`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/sell-house-fast-york-pa-2026`, priority: 1.0, changeFrequency: 'monthly' as const },
    // Wilmington DE
    { url: `${baseUrl}/markets/wilmington-de`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/wilmington-de/market-report`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/wilmington-de/inherited-property`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/wilmington-de/foreclosure`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/wilmington-de/divorce-sale`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/wilmington-de/probate`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/wilmington-de/tenant-occupied`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/wilmington-de/code-violations`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/wilmington-de/fire-damage`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/wilmington-de/faq`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/wilmington-de/neighborhoods`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/sell-house-fast-wilmington-de-2026`, priority: 1.0, changeFrequency: 'monthly' as const },
    // Delaware state hub
    { url: `${baseUrl}/sell-house-fast-delaware`, priority: 0.9, changeFrequency: 'monthly' as const },
    // Youngstown OH
    { url: `${baseUrl}/markets/youngstown-oh`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/youngstown-oh/market-report`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/youngstown-oh/inherited-property`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/youngstown-oh/foreclosure`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/youngstown-oh/divorce-sale`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/youngstown-oh/probate`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/youngstown-oh/tenant-occupied`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/youngstown-oh/code-violations`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/youngstown-oh/fire-damage`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/youngstown-oh/faq`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/youngstown-oh/neighborhoods`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/sell-house-fast-youngstown-oh-2026`, priority: 1.0, changeFrequency: 'monthly' as const },
    // Ohio state hub
    { url: `${baseUrl}/sell-house-fast-ohio`, priority: 0.9, changeFrequency: 'monthly' as const },
    // Springfield MA
    { url: `${baseUrl}/markets/springfield-ma`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/springfield-ma/market-report`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/springfield-ma/inherited-property`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/springfield-ma/foreclosure`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/springfield-ma/divorce-sale`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/springfield-ma/probate`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/springfield-ma/tenant-occupied`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/springfield-ma/code-violations`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/springfield-ma/fire-damage`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/springfield-ma/faq`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/springfield-ma/neighborhoods`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/sell-house-fast-springfield-ma-2026`, priority: 1.0, changeFrequency: 'monthly' as const },
    // Kenosha WI
    { url: `${baseUrl}/markets/kenosha-wi`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/kenosha-wi/market-report`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/kenosha-wi/inherited-property`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/kenosha-wi/foreclosure`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/kenosha-wi/divorce-sale`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/kenosha-wi/probate`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/kenosha-wi/tenant-occupied`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/kenosha-wi/code-violations`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/kenosha-wi/fire-damage`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/kenosha-wi/faq`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/kenosha-wi/neighborhoods`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/sell-house-fast-kenosha-wi-2026`, priority: 1.0, changeFrequency: 'monthly' as const },
    // Racine-Mount Pleasant WI
    { url: `${baseUrl}/markets/racine-mount-pleasant-wi`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/racine-mount-pleasant-wi/market-report`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/racine-mount-pleasant-wi/inherited-property`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/racine-mount-pleasant-wi/foreclosure`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/racine-mount-pleasant-wi/divorce-sale`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/racine-mount-pleasant-wi/probate`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/racine-mount-pleasant-wi/tenant-occupied`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/racine-mount-pleasant-wi/code-violations`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/racine-mount-pleasant-wi/fire-damage`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/racine-mount-pleasant-wi/faq`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/racine-mount-pleasant-wi/neighborhoods`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/sell-house-fast-racine-mount-pleasant-wi-2026`, priority: 1.0, changeFrequency: 'monthly' as const },
    // Manchester NH
    { url: `${baseUrl}/markets/manchester-nh`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/manchester-nh/market-report`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/manchester-nh/inherited-property`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/manchester-nh/foreclosure`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/manchester-nh/divorce-sale`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/manchester-nh/probate`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/manchester-nh/tenant-occupied`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/manchester-nh/code-violations`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/manchester-nh/fire-damage`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/manchester-nh/faq`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/manchester-nh/neighborhoods`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/sell-house-fast-manchester-nh-2026`, priority: 1.0, changeFrequency: 'monthly' as const },
    // Bridgeport CT
    { url: `${baseUrl}/markets/bridgeport-ct`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bridgeport-ct/market-report`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bridgeport-ct/inherited-property`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bridgeport-ct/foreclosure`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bridgeport-ct/divorce-sale`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bridgeport-ct/probate`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bridgeport-ct/tenant-occupied`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bridgeport-ct/code-violations`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bridgeport-ct/fire-damage`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bridgeport-ct/faq`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bridgeport-ct/neighborhoods`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/sell-house-fast-bridgeport-ct-2026`, priority: 1.0, changeFrequency: 'monthly' as const },
    // Worcester MA
    { url: `${baseUrl}/markets/worcester-ma`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/worcester-ma/market-report`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/worcester-ma/inherited-property`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/worcester-ma/foreclosure`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/worcester-ma/divorce-sale`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/worcester-ma/probate`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/worcester-ma/tenant-occupied`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/worcester-ma/code-violations`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/worcester-ma/fire-damage`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/worcester-ma/faq`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/worcester-ma/neighborhoods`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/sell-house-fast-worcester-ma-2026`, priority: 1.0, changeFrequency: 'monthly' as const },
    // Rochester NY
    { url: `${baseUrl}/markets/rochester-ny`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/rochester-ny/market-report`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/rochester-ny/inherited-property`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/rochester-ny/foreclosure`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/rochester-ny/divorce-sale`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/rochester-ny/probate`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/rochester-ny/tenant-occupied`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/rochester-ny/code-violations`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/rochester-ny/fire-damage`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/rochester-ny/faq`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/rochester-ny/neighborhoods`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/sell-house-fast-rochester-ny-2026`, priority: 1.0, changeFrequency: 'monthly' as const },
    // Springfield IL market
    { url: `${baseUrl}/markets/springfield-il`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/springfield-il/market-report`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/springfield-il/inherited-property`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/springfield-il/foreclosure`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/springfield-il/divorce-sale`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/springfield-il/probate`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/springfield-il/tenant-occupied`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/springfield-il/code-violations`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/springfield-il/fire-damage`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/springfield-il/faq`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/springfield-il/neighborhoods`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/sell-house-fast-springfield-il-2026`, priority: 0.8, changeFrequency: 'monthly' as const },
    // New state hubs
    { url: `${baseUrl}/sell-house-fast-massachusetts`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/sell-house-fast-wisconsin`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/sell-house-fast-new-hampshire`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/sell-house-fast-connecticut`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/sell-house-fast-new-york`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/sell-house-fast-illinois`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/blog`, priority: 0.8, changeFrequency: 'weekly' as const },
    { url: `${baseUrl}/blog/sell-inherited-house-pennsylvania`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/blog/sell-house-with-code-violations-pa`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/blog/cash-buyer-vs-realtor-pennsylvania`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/blog/probate-timeline-pennsylvania`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/blog/closing-costs-selling-house-pennsylvania`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/blog/sell-house-foreclosure-pennsylvania`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/blog/sell-house-tax-lien-pennsylvania`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/blog/springfield-il-sell-house-fast-2026`, priority: 0.7, changeFrequency: 'monthly' as const },
    // Rockford IL
    { url: `${baseUrl}/markets/rockford-il`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/rockford-il/market-report`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/rockford-il/faq`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/rockford-il/neighborhoods`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/rockford-il/inherited-property`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/rockford-il/foreclosure`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/rockford-il/divorce-sale`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/rockford-il/probate`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/rockford-il/tenant-occupied`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/rockford-il/code-violations`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/rockford-il/fire-damage`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/sell-house-fast-rockford-il-2026`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/blog/rockford-il-sell-house-fast-2026`, priority: 0.7, changeFrequency: 'monthly' as const },
    // New Haven CT
    { url: `${baseUrl}/markets/new-haven-ct`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/new-haven-ct/market-report`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/new-haven-ct/faq`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/new-haven-ct/neighborhoods`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/new-haven-ct/inherited-property`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/new-haven-ct/foreclosure`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/new-haven-ct/divorce-sale`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/new-haven-ct/probate`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/new-haven-ct/tenant-occupied`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/new-haven-ct/code-violations`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/new-haven-ct/fire-damage`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/sell-house-fast-new-haven-ct-2026`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/blog/new-haven-ct-sell-house-fast-2026`, priority: 0.7, changeFrequency: 'monthly' as const },
    // Hartford CT
    { url: `${baseUrl}/markets/hartford-ct`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/hartford-ct/market-report`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/hartford-ct/inherited-property`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/hartford-ct/foreclosure`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/hartford-ct/divorce-sale`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/hartford-ct/probate`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/hartford-ct/tenant-occupied`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/hartford-ct/code-violations`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/hartford-ct/fire-damage`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/hartford-ct/faq`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/hartford-ct/neighborhoods`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/sell-house-fast-hartford-ct-2026`, priority: 1.0, changeFrequency: 'monthly' as const },
    // Boston MA
    { url: `${baseUrl}/markets/boston-ma`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/boston-ma/market-report`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/boston-ma/inherited-property`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/boston-ma/foreclosure`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/boston-ma/divorce-sale`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/boston-ma/probate`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/boston-ma/tenant-occupied`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/boston-ma/code-violations`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/boston-ma/fire-damage`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/boston-ma/faq`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/boston-ma/neighborhoods`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/sell-house-fast-boston-ma-2026`, priority: 1.0, changeFrequency: 'monthly' as const },
    // Oshkosh WI (market #21)
    { url: `${baseUrl}/markets/oshkosh-wi`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/oshkosh-wi/market-report`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/oshkosh-wi/faq`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/oshkosh-wi/neighborhoods`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/oshkosh-wi/inherited-property`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/oshkosh-wi/foreclosure`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/oshkosh-wi/divorce-sale`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/oshkosh-wi/probate`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/oshkosh-wi/tenant-occupied`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/oshkosh-wi/code-violations`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/oshkosh-wi/fire-damage`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/sell-house-fast-oshkosh-wi-2026`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/blog/oshkosh-wi-sell-house-fast-2026`, priority: 0.7, changeFrequency: 'monthly' as const },
    // Peoria IL (market #23)
    { url: `${baseUrl}/markets/peoria-il`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/peoria-il/market-report`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/peoria-il/faq`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/peoria-il/neighborhoods`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/peoria-il/inherited-property`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/peoria-il/foreclosure`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/peoria-il/divorce-sale`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/peoria-il/probate`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/peoria-il/tenant-occupied`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/peoria-il/code-violations`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/peoria-il/fire-damage`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/sell-house-fast-peoria-il-2026`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/blog/peoria-il-sell-house-fast-2026`, priority: 0.7, changeFrequency: 'monthly' as const },
    // Bloomington IL (market #24)
    { url: `${baseUrl}/markets/bloomington-il`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bloomington-il/market-report`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bloomington-il/faq`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bloomington-il/neighborhoods`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bloomington-il/inherited-property`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bloomington-il/foreclosure`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bloomington-il/divorce-sale`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bloomington-il/probate`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bloomington-il/tenant-occupied`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bloomington-il/code-violations`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/bloomington-il/fire-damage`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/sell-house-fast-bloomington-il-2026`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/blog/bloomington-il-sell-house-fast-2026`, priority: 0.7, changeFrequency: 'monthly' as const },
    // Champaign-Urbana IL (market #25)
    { url: `${baseUrl}/markets/champaign-urbana-il`, priority: 1.0, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/champaign-urbana-il/market-report`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/champaign-urbana-il/faq`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/champaign-urbana-il/neighborhoods`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/champaign-urbana-il/inherited-property`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/champaign-urbana-il/foreclosure`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/champaign-urbana-il/divorce-sale`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/champaign-urbana-il/probate`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/champaign-urbana-il/tenant-occupied`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/champaign-urbana-il/code-violations`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/markets/champaign-urbana-il/fire-damage`, priority: 0.9, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/guides/sell-house-fast-champaign-urbana-il-2026`, priority: 0.8, changeFrequency: 'monthly' as const },
    { url: `${baseUrl}/blog/champaign-urbana-il-sell-house-fast-2026`, priority: 0.7, changeFrequency: 'monthly' as const },
  ];

  return pages.map((page) => ({
    url: page.url,
    lastModified: new Date(),
    changeFrequency: page.changeFrequency,
    priority: page.priority,
  }));
}
