/**
 * lib/blog.ts — Blog content registry
 * 
 * Source of truth for all blog post metadata.
 * Existing 3 posts: static TSX in app/blog/[slug]/
 * New posts: rendered via dynamic [slug]/page.tsx using content from this registry
 */

export interface BlogPostMeta {
  slug: string;
  title: string;
  excerpt: string;
  date: string;
  datePublished: string;
  category: string;
  readTime: string;
  heroImage: string;
  heroAlt: string;
  description: string;
  primaryKeyword: string;
  markets: string[];
  /** true = uses static TSX page, false = uses dynamic renderer */
  isStatic?: boolean;
}

export const BLOG_POSTS: BlogPostMeta[] = [
  {
    slug: 'sell-inherited-house-pennsylvania',
    title: 'How to Sell an Inherited House in Pennsylvania',
    excerpt:
      "Inheriting a house is equal parts gift and burden. Here's what you need to know about probate, taxes, multiple heirs, and selling as-is.",
    date: 'April 9, 2026',
    datePublished: '2026-04-09',
    category: 'Inherited Property',
    readTime: '8 min',
    heroImage: '/images/harrisburg-hero.jpg',
    heroAlt: 'Pennsylvania home — inherited property sale',
    description:
      'Inherited a house in Pennsylvania? Learn your options — sell as-is, probate requirements, tax implications, and how to close fast without family drama.',
    primaryKeyword: 'sell inherited house Pennsylvania',
    markets: ['harrisburg-pa', 'allentown-pa', 'bethlehem-pa', 'erie-pa', 'king-of-prussia-pa', 'lancaster-pa', 'reading-pa', 'state-college-pa', 'york-pa'],
    isStatic: true,
  },
  {
    slug: 'sell-house-with-code-violations-pa',
    title: 'Selling a House With Code Violations in Pennsylvania',
    excerpt:
      "Open permits, point-of-sale inspections, failed systems — code violations don't have to stop your sale. Learn how cash buyers handle them.",
    date: 'April 10, 2026',
    datePublished: '2026-04-10',
    category: 'Code Violations',
    readTime: '7 min',
    heroImage: '/images/harrisburg-hero.jpg',
    heroAlt: 'Pennsylvania house with code violations',
    description:
      'Selling a house with code violations in PA? Cash buyers purchase as-is — no repairs required. Learn about point-of-sale inspections, open permits, and your options.',
    primaryKeyword: 'sell house with code violations Pennsylvania',
    markets: ['harrisburg-pa', 'allentown-pa', 'bethlehem-pa', 'erie-pa', 'king-of-prussia-pa', 'lancaster-pa', 'reading-pa', 'state-college-pa', 'york-pa'],
    isStatic: true,
  },
  {
    slug: 'cash-buyer-vs-realtor-pennsylvania',
    title: "Cash Buyer vs. Realtor in Pennsylvania: What's the Real Difference?",
    excerpt:
      'An honest, numbers-based comparison of cash buyers vs. real estate agents in PA. When each option wins — no spin.',
    date: 'April 11, 2026',
    datePublished: '2026-04-11',
    category: 'Comparison',
    readTime: '9 min',
    heroImage: '/images/harrisburg-hero.jpg',
    heroAlt: 'Comparing cash buyer vs realtor in Pennsylvania',
    description:
      'Cash buyer or realtor — which gets you more in Pennsylvania? Real numbers, real timelines, and an honest breakdown of when each option makes sense.',
    primaryKeyword: 'cash buyer vs realtor Pennsylvania',
    markets: ['harrisburg-pa', 'allentown-pa', 'bethlehem-pa', 'erie-pa', 'king-of-prussia-pa', 'lancaster-pa', 'reading-pa', 'state-college-pa', 'york-pa'],
    isStatic: true,
  },
  {
    slug: 'probate-timeline-pennsylvania',
    title: 'How Long Does Probate Take in Pennsylvania? County-by-County Breakdown',
    excerpt:
      'Pennsylvania probate takes 9-18 months for simple estates. Here\'s what actually drives the timeline — and how to sell a house before probate closes.',
    date: 'April 15, 2026',
    datePublished: '2026-04-15',
    category: 'Probate',
    readTime: '7 min',
    heroImage: '/images/harrisburg-hero.jpg',
    heroAlt: 'Pennsylvania probate courthouse — Dauphin County Register of Wills',
    description:
      'How long does probate take in Pennsylvania? County-by-county breakdown of timelines, what drives delays, and how to sell a house during or after probate.',
    primaryKeyword: 'how long does probate take in Pennsylvania',
    markets: ['harrisburg-pa', 'allentown-pa', 'bethlehem-pa', 'erie-pa', 'king-of-prussia-pa', 'lancaster-pa', 'reading-pa', 'state-college-pa', 'york-pa'],
    isStatic: false,
  },
  {
    slug: 'closing-costs-selling-house-pennsylvania',
    title: 'What Are Closing Costs When Selling a House in PA? [2026 Numbers]',
    excerpt:
      'Real closing cost numbers for Pennsylvania sellers in 2026. Transfer taxes, agent commissions, title fees — here\'s what actually comes out of your check.',
    date: 'April 16, 2026',
    datePublished: '2026-04-16',
    category: 'Education',
    readTime: '8 min',
    heroImage: '/images/harrisburg-hero.jpg',
    heroAlt: 'Pennsylvania home sale closing costs breakdown',
    description:
      'What are closing costs when selling a house in PA? Real 2026 numbers — transfer tax, commissions, title fees, and how cash buyers handle costs differently.',
    primaryKeyword: 'closing costs selling house Pennsylvania',
    markets: ['harrisburg-pa', 'allentown-pa', 'bethlehem-pa', 'erie-pa', 'king-of-prussia-pa', 'lancaster-pa', 'reading-pa', 'state-college-pa', 'york-pa'],
    isStatic: false,
  },
  {
    slug: 'sell-house-foreclosure-pennsylvania',
    title: 'Can You Sell a House in Foreclosure in Pennsylvania?',
    excerpt:
      "Yes — up until the sheriff's sale. Pennsylvania's 12-24 month judicial foreclosure process gives you time to sell. Here's exactly how it works.",
    date: 'April 17, 2026',
    datePublished: '2026-04-17',
    category: 'Foreclosure',
    readTime: '8 min',
    heroImage: '/images/harrisburg-hero.jpg',
    heroAlt: 'Pennsylvania home in foreclosure — sell before sheriff sale',
    description:
      "Can you sell a house in foreclosure in Pennsylvania? Yes — right up until the sheriff's sale. Learn how to stop foreclosure with a fast sale.",
    primaryKeyword: 'sell house in foreclosure Pennsylvania',
    markets: ['harrisburg-pa', 'allentown-pa', 'bethlehem-pa', 'erie-pa', 'king-of-prussia-pa', 'lancaster-pa', 'reading-pa', 'state-college-pa', 'york-pa'],
    isStatic: false,
  },
  {
    slug: 'sell-house-tax-lien-pennsylvania',
    title: 'Selling a House with a Tax Lien in PA: Your Options',
    excerpt:
      "A tax lien doesn't mean you can't sell — it means the lien gets paid at closing. Here's how federal, state, and local liens work in Pennsylvania.",
    date: 'April 18, 2026',
    datePublished: '2026-04-18',
    category: 'Education',
    readTime: '7 min',
    heroImage: '/images/harrisburg-hero.jpg',
    heroAlt: 'Pennsylvania property with tax lien — selling options',
    description:
      'Selling a house with a tax lien in PA? Federal, state, and local liens all get paid at closing. Learn your options and how cash buyers simplify the process.',
    primaryKeyword: 'sell house with tax lien Pennsylvania',
    markets: ['harrisburg-pa', 'allentown-pa', 'bethlehem-pa', 'erie-pa', 'king-of-prussia-pa', 'lancaster-pa', 'reading-pa', 'state-college-pa', 'york-pa'],
    isStatic: false,
  },
  {
    slug: 'sell-house-divorce-pennsylvania',
    title: 'How to Sell a House in Divorce in Pennsylvania',
    excerpt:
      "Equitable distribution, buyouts, tax timing — here's everything divorcing PA homeowners need to know about the family home.",
    date: 'April 16, 2026',
    datePublished: '2026-04-16',
    category: 'Divorce',
    readTime: '9 min',
    heroImage: '/images/harrisburg-hero.jpg',
    heroAlt: 'Pennsylvania home — selling in divorce',
    description:
      'How to sell a house in divorce in Pennsylvania. Equitable distribution rules, buyout options, tax implications, and why cash buyers simplify the process.',
    primaryKeyword: 'how to sell a house in divorce in Pennsylvania',
    markets: ['harrisburg-pa', 'allentown-pa', 'bethlehem-pa', 'erie-pa', 'king-of-prussia-pa', 'lancaster-pa', 'reading-pa', 'state-college-pa', 'york-pa'],
    isStatic: false,
  },
  {
    slug: 'selling-tenant-occupied-property-pa',
    title: "Selling a Tenant-Occupied Property in Pennsylvania: A Landlord's Guide",
    excerpt:
      "Your tenants have rights that affect your sale — but they don't stop it. Here's what PA landlord-tenant law actually says.",
    date: 'April 16, 2026',
    datePublished: '2026-04-16',
    category: 'Landlord',
    readTime: '10 min',
    heroImage: '/images/harrisburg-hero.jpg',
    heroAlt: 'Tenant-occupied rental property in Pennsylvania',
    description:
      'Selling a tenant-occupied property in Pennsylvania? Leases survive the sale, tenants have notice rights, and cash for keys can speed things up. Full landlord guide.',
    primaryKeyword: 'selling tenant-occupied property Pennsylvania',
    markets: ['harrisburg-pa', 'allentown-pa', 'bethlehem-pa', 'erie-pa', 'king-of-prussia-pa', 'lancaster-pa', 'reading-pa', 'state-college-pa', 'york-pa'],
    isStatic: false,
  },
  {
    slug: 'property-taxes-pennsylvania-what-happens',
    title: "What Happens If You Don't Pay Property Taxes in Pennsylvania?",
    excerpt:
      "Upset Sales, Judicial Sales, and a multi-year process before you lose your home. Here's what delinquent PA property taxes actually mean.",
    date: 'April 16, 2026',
    datePublished: '2026-04-16',
    category: 'Education',
    readTime: '9 min',
    heroImage: '/images/harrisburg-hero.jpg',
    heroAlt: 'Pennsylvania property tax delinquency — what sellers need to know',
    description:
      "What happens if you don't pay property taxes in Pennsylvania? Upset Sales, Judicial Sales, redemption rights, and how to sell before losing your home.",
    primaryKeyword: "what happens if you don't pay property taxes in Pennsylvania",
    markets: ['harrisburg-pa', 'allentown-pa', 'bethlehem-pa', 'erie-pa', 'king-of-prussia-pa', 'lancaster-pa', 'reading-pa', 'state-college-pa', 'york-pa'],
    isStatic: false,
  },
  {
    slug: 'destroyed-rental-property-case-study',
    title: 'He Thought His Destroyed Rental Was Worthless — He Walked Away With $50,000',
    excerpt:
      "His tenant ran a drug operation out of the property. Police raided it. He moved to Massachusetts and had no idea what to do. Here's how it ended.",
    date: 'April 16, 2026',
    datePublished: '2026-04-16',
    category: 'Case Study',
    readTime: '10 min',
    heroImage: '/images/harrisburg-hero.jpg',
    heroAlt: 'Destroyed rental property Pennsylvania — sold for cash as-is',
    description:
      'A Pennsylvania landlord\'s rental was destroyed by a tenant after a drug raid. He was out of state with no idea what to do. A mobile notary closed the deal at his kitchen table — he walked away with $50,000.',
    primaryKeyword: 'sell destroyed rental property Pennsylvania',
    markets: ['harrisburg-pa', 'allentown-pa', 'bethlehem-pa', 'erie-pa', 'king-of-prussia-pa', 'lancaster-pa', 'reading-pa', 'state-college-pa', 'york-pa', 'wilmington-de', 'youngstown-oh'],
    isStatic: false,
  },


  {
    slug: 'how-to-sell-house-fast-massachusetts',
    title: 'How to Sell a House Fast in Massachusetts',
    excerpt: 'Massachusetts sellers face deed excise stamps, attorney-driven closings, and non-judicial foreclosure timelines. Here is how an as-is cash sale works.',
    date: 'April 18, 2026',
    datePublished: '2026-04-18',
    category: 'Education',
    readTime: '8 min',
    heroImage: '/images/springfield-ma-hero.jpg',
    heroAlt: 'Massachusetts home — sell fast for cash',
    description: 'Massachusetts sellers face deed excise stamps, attorney-driven closings, and non-judicial foreclosure timelines. Here is how an as-is cash sale works.',
    primaryKeyword: 'sell house fast Massachusetts',
    markets: ['springfield-ma', 'worcester-ma', 'boston-ma'],
    isStatic: false,
  },
  {
    slug: 'selling-inherited-property-new-england',
    title: 'Selling Inherited Property in New England',
    excerpt: 'Probate, multiple heirs, repairs, and as-is sale options for inherited homes in Massachusetts, Connecticut, and New Hampshire.',
    date: 'April 18, 2026',
    datePublished: '2026-04-18',
    category: 'Inherited Property',
    readTime: '8 min',
    heroImage: '/images/worcester-ma-hero.jpg',
    heroAlt: 'New England inherited property — cash sale options',
    description: 'Probate, multiple heirs, repairs, and as-is sale options for inherited homes in Massachusetts, Connecticut, and New Hampshire.',
    primaryKeyword: 'sell inherited property New England',
    markets: ['springfield-ma', 'worcester-ma', 'boston-ma', 'bridgeport-ct', 'new-haven-ct', 'hartford-ct', 'manchester-nh'],
    isStatic: false,
  },
  {
    slug: 'champaign-urbana-il-sell-house-fast-2026',
    title: 'Selling Your House Fast in Champaign-Urbana IL in 2026 — What UIUC Sellers Need to Know',
    excerpt: 'UIUC faculty relocations, tired student-rental landlords, the 0.15% transfer tax confusion — what makes selling in Champaign-Urbana different from every other Illinois market.',
    date: 'April 18, 2026',
    datePublished: '2026-04-18',
    category: 'Market Guide',
    readTime: '8 min',
    heroImage: '/images/champaign-urbana-il-hero.jpg',
    heroAlt: 'Champaign-Urbana IL home — sell fast for cash',
    description: 'UIUC faculty relocations, tired student-rental landlords, the 0.15% transfer tax confusion — what makes selling in Champaign-Urbana different from every other Illinois market.',
    primaryKeyword: 'sell house fast Champaign-Urbana IL',
    markets: ['champaign-urbana-il', 'bloomington-il', 'springfield-il'],
    isStatic: true,
  },
  {
    slug: 'new-haven-ct-sell-house-fast-2026',
    title: 'New Haven CT: Sell House Fast in 2026',
    excerpt: 'New Haven CT\'s housing market in 2026: what sellers need to know about CT strict foreclosure, 1.25% conveyance tax, and why pre-war homes need cash buyers.',
    date: 'April 18, 2026',
    datePublished: '2026-04-18',
    category: 'Market Guide',
    readTime: '8 min',
    heroImage: '/images/new-haven-ct-hero.jpg',
    heroAlt: 'New Haven CT house — sell fast for cash',
    description: 'New Haven CT\'s housing market in 2026: what sellers need to know about CT strict foreclosure, 1.25% conveyance tax, and why pre-war homes need cash buyers.',
    primaryKeyword: 'sell house fast New Haven CT',
    markets: ['new-haven-ct', 'bridgeport-ct', 'hartford-ct'],
    isStatic: true,
  },
  {
    slug: 'oshkosh-wi-sell-house-fast-2026',
    title: 'Oshkosh WI: Sell House Fast in 2026',
    excerpt: 'Oshkosh WI\'s housing market is #13 in the US — but older homes still need cash buyers. What Winnebago County sellers need to know in 2026: market data, WI transfer fee, foreclosure.',
    date: 'April 18, 2026',
    datePublished: '2026-04-18',
    category: 'Market Guide',
    readTime: '8 min',
    heroImage: '/images/oshkosh-wi-hero.jpg',
    heroAlt: 'Oshkosh WI home — sell fast for cash',
    description: 'Oshkosh WI\'s housing market is #13 in the US — but older homes still need cash buyers. What Winnebago County sellers need to know in 2026: market data, WI transfer fee, foreclosure.',
    primaryKeyword: 'sell house fast Oshkosh WI',
    markets: ['oshkosh-wi', 'wausau-wi'],
    isStatic: true,
  },
  {
    slug: 'peoria-il-sell-house-fast-2026',
    title: 'Peoria IL: Why Cash Buyers Are Winning the Entry-Level Market in 2026',
    excerpt: 'Peoria IL\'s $115,649 ZHVI, 24.3% pre-1940 housing stock, and unique $500 municipal transfer tax create a distinct cash buyer opportunity. Data and analysis for 2026.',
    date: 'April 18, 2026',
    datePublished: '2026-04-18',
    category: 'Market Guide',
    readTime: '8 min',
    heroImage: '/images/peoria-il-hero.jpg',
    heroAlt: 'Peoria IL house — sell fast for cash',
    description: 'Peoria IL\'s $115,649 ZHVI, 24.3% pre-1940 housing stock, and unique $500 municipal transfer tax create a distinct cash buyer opportunity. Data and analysis for 2026.',
    primaryKeyword: 'sell house fast Peoria IL',
    markets: ['peoria-il', 'bloomington-il', 'springfield-il', 'rockford-il', 'champaign-urbana-il'],
    isStatic: true,
  },
  {
    slug: 'rockford-il-sell-house-fast-2026',
    title: 'Rockford IL: Sell House Fast in 2026',
    excerpt: 'Rockford IL\'s housing market is #11 in the US — but older homes still need cash buyers. What sellers need to know in 2026: market data, transfer taxes, foreclosure timelines.',
    date: 'April 18, 2026',
    datePublished: '2026-04-18',
    category: 'Market Guide',
    readTime: '8 min',
    heroImage: '/images/rockford-il-hero.jpg',
    heroAlt: 'Rockford IL house — sell fast for cash',
    description: 'Rockford IL\'s housing market is #11 in the US — but older homes still need cash buyers. What sellers need to know in 2026: market data, transfer taxes, foreclosure timelines.',
    primaryKeyword: 'sell house fast Rockford IL',
    markets: ['rockford-il', 'springfield-il', 'peoria-il', 'bloomington-il', 'champaign-urbana-il'],
    isStatic: true,
  },
  {
    slug: 'springfield-il-sell-house-fast-2026',
    title: 'Why Springfield IL Is the #10 Hottest US Market in 2026',
    excerpt: 'Springfield IL ranked #10 hottest US market (RDC, March 2026). What it means for sellers, why older homes still need cash buyers, and how to move fast.',
    date: 'April 18, 2026',
    datePublished: '2026-04-18',
    category: 'Market Guide',
    readTime: '8 min',
    heroImage: '/images/springfield-il-hero.jpg',
    heroAlt: 'Springfield IL home — sell fast for cash',
    description: 'Springfield IL ranked #10 hottest US market (RDC, March 2026). What it means for sellers, why older homes still need cash buyers, and how to move fast.',
    primaryKeyword: 'sell house fast Springfield IL',
    markets: ['springfield-il', 'bloomington-il', 'peoria-il', 'rockford-il', 'champaign-urbana-il'],
    isStatic: true,
  },
  {
    slug: 'bloomington-il-sell-house-fast-2026',
    title: 'Bloomington IL: Sell House Fast in 2026',
    excerpt: 'Bloomington IL\'s insurance-capital market is #27 nationally — but not every home benefits from the hot market. What sellers need to know about cash buyers, transfer taxes, and the State Farm factor.',
    date: 'April 19, 2026',
    datePublished: '2026-04-19',
    category: 'Market Guide',
    readTime: '8 min',
    heroImage: '/images/bloomington-il-hero.jpg',
    heroAlt: 'Bloomington IL house — sell fast for cash',
    description: 'Bloomington IL\'s insurance-capital market is #27 nationally — but not every home benefits from the hot market. What sellers need to know about cash buyers, transfer taxes, and the State Farm factor.',
    primaryKeyword: 'sell house fast Bloomington IL',
    markets: ['bloomington-il', 'springfield-il', 'peoria-il', 'rockford-il', 'champaign-urbana-il'],
    isStatic: true,
  },
  {
    slug: 'harrisburg-pa-sell-house-fast-2026',
    title: 'Harrisburg PA: Sell Your House Fast in 2026',
    excerpt: 'Harrisburg PA\'s two-tier market leaves some sellers stranded. What cash buyers, PA transfer taxes, judicial foreclosure, and Dauphin County probate mean for you in 2026.',
    date: 'April 20, 2026',
    datePublished: '2026-04-20',
    category: 'Market Guide',
    readTime: '8 min',
    heroImage: '/images/harrisburg-hero.jpg',
    heroAlt: 'Harrisburg PA home — selling fast for cash',
    description: 'Harrisburg PA\'s two-tier market leaves some sellers stranded. What cash buyers, PA transfer taxes, judicial foreclosure, and Dauphin County probate mean for you in 2026.',
    primaryKeyword: 'sell house fast Harrisburg PA',
    markets: ['harrisburg-pa'],
    isStatic: true,
  },
  {
    slug: 'sell-inherited-house-illinois',
    title: 'Selling an Inherited House in Illinois (2026)',
    excerpt: 'Inherited a house in Illinois? Probate timelines, the no-inheritance-tax advantage, step-up in basis, and how to sell fast in Springfield, Bloomington, or Peoria.',
    date: 'April 21, 2026',
    datePublished: '2026-04-21',
    category: 'Inherited Property',
    readTime: '8 min',
    heroImage: '/images/springfield-il-hero.jpg',
    heroAlt: 'Illinois inherited house — probate and cash sale options',
    description: 'Inherited a house in Illinois? Probate timelines, the no-inheritance-tax advantage, step-up in basis, and how to sell fast in Springfield, Bloomington, or Peoria.',
    primaryKeyword: 'sell inherited house Illinois',
    markets: ['springfield-il', 'bloomington-il', 'peoria-il', 'rockford-il', 'champaign-urbana-il'],
    isStatic: true,
  },
  {
    slug: 'youngstown-oh-housing-market-april-2026',
    title: 'Youngstown OH Housing Market: April 2026',
    excerpt: 'Youngstown city median hit $93K in March 2026 — but Boardman is $172K, Canfield $294K. What the city vs. suburb data split means if you need to sell.',
    date: 'April 22, 2026',
    datePublished: '2026-04-22',
    category: 'Market Report',
    readTime: '7 min',
    heroImage: '/images/youngstown-oh-hero.jpg',
    heroAlt: 'Youngstown OH housing market update',
    description: 'Youngstown city median hit $93K in March 2026 — but Boardman is $172K, Canfield $294K. What the city vs. suburb data split means if you need to sell.',
    primaryKeyword: 'Youngstown OH housing market April 2026',
    markets: ['youngstown-oh'],
    isStatic: true,
  },
  {
    slug: 'what-happens-after-accepting-cash-offer',
    title: 'What Happens After You Accept a Cash Offer?',
    excerpt: 'You signed. Now what? A plain-English walkthrough of every step from accepted offer to cash in hand — title search, closing day, and what to expect.',
    date: 'April 23, 2026',
    datePublished: '2026-04-23',
    category: 'Process',
    readTime: '7 min',
    heroImage: '/images/harrisburg-hero.jpg',
    heroAlt: 'Cash home sale paperwork after accepting an offer',
    description: 'You signed. Now what? A plain-English walkthrough of every step from accepted offer to cash in hand — title search, closing day, and what to expect.',
    primaryKeyword: 'what happens after accepting cash offer on house',
    markets: ['harrisburg-pa', 'allentown-pa', 'rochester-ny', 'springfield-il', 'kenosha-wi', 'wilmington-de', 'youngstown-oh'],
    isStatic: true,
  },
  {
    slug: 'allentown-pa-sell-house-fast-2026',
    title: 'Sell Your House Fast in Allentown PA (2026)',
    excerpt: 'Allentown\'s hot market averages 6 offers on updated homes — but the South Side tells a different story. What Lehigh Valley sellers need to know in 2026.',
    date: 'April 24, 2026',
    datePublished: '2026-04-24',
    category: 'Market Guide',
    readTime: '8 min',
    heroImage: '/images/allentown-hero.jpg',
    heroAlt: 'Allentown PA home — selling fast for cash',
    description: 'Allentown\'s hot market averages 6 offers on updated homes — but the South Side tells a different story. What Lehigh Valley sellers need to know in 2026.',
    primaryKeyword: 'sell house fast Allentown PA',
    markets: ['allentown-pa', 'bethlehem-pa'],
    isStatic: true,
  },
  {
    slug: 'selling-house-during-divorce-pennsylvania',
    title: 'Selling a House During Divorce in Pennsylvania',
    excerpt: 'Divorcing in Pennsylvania? Here is how the marital home gets handled, when you can sell, and what Harrisburg, Reading, and Lancaster sellers should know.',
    date: 'April 25, 2026',
    datePublished: '2026-04-25',
    category: 'Divorce',
    readTime: '8 min',
    heroImage: '/images/harrisburg-hero.jpg',
    heroAlt: 'Pennsylvania home — selling during divorce',
    description: 'Divorcing in Pennsylvania? Here is how the marital home gets handled, when you can sell, and what Harrisburg, Reading, and Lancaster sellers should know.',
    primaryKeyword: 'selling house during divorce Pennsylvania',
    markets: ['harrisburg-pa', 'reading-pa', 'lancaster-pa', 'allentown-pa', 'york-pa'],
    isStatic: true,
  },
  {
    slug: 'kenosha-vs-racine-housing-market-2026',
    title: 'Kenosha vs Racine Housing Market 2026',
    excerpt: 'Kenosha vs Racine WI housing market comparison for sellers: prices, demand, condition issues, and when a cash offer makes sense.',
    date: 'April 26, 2026',
    datePublished: '2026-04-26',
    category: 'Market Report',
    readTime: '7 min',
    heroImage: '/images/kenosha-wi-hero.jpg',
    heroAlt: 'Kenosha and Racine WI housing market comparison',
    description: 'Kenosha vs Racine WI housing market comparison for sellers: prices, demand, condition issues, and when a cash offer makes sense.',
    primaryKeyword: 'Kenosha vs Racine housing market 2026',
    markets: ['kenosha-wi', 'racine-mount-pleasant-wi', 'oshkosh-wi', 'wausau-wi'],
    isStatic: true,
  },
  {
    slug: 'rochester-ny-sell-house-fast-2026',
    title: 'Sell Your House Fast in Rochester NY (2026)',
    excerpt: 'Rochester NY homes sell in 14 days and 9% above list. Not every house qualifies. What Kodak-era sellers, estate heirs, and pre-foreclosure owners need to know.',
    date: 'April 28, 2026',
    datePublished: '2026-04-28',
    category: 'Market Guide',
    readTime: '8 min',
    heroImage: '/images/rochester-ny-hero.jpg',
    heroAlt: 'Rochester NY home — selling fast for cash',
    description: 'Rochester NY homes sell in 14 days and 9% above list. Not every house qualifies. What Kodak-era sellers, estate heirs, and pre-foreclosure owners need to know.',
    primaryKeyword: 'sell house fast Rochester NY',
    markets: ['rochester-ny'],
    isStatic: true,
  },
  {
    slug: 'sell-flood-damaged-house-allentown-pa',
    title: 'Selling a Flood-Damaged House in Allentown PA — Jordan Creek, Little Lehigh, and What Sellers Can Do',
    excerpt: "If you own a house near Jordan Creek, Little Lehigh Creek, or Allentown's low-lying creek corridors, flood damage can stop a normal sale fast. Here's what to do.",
    date: 'April 30, 2026',
    datePublished: '2026-04-30',
    category: 'Situation Deep-Dive',
    readTime: '7 min',
    heroImage: '/images/allentown-hero.jpg',
    heroAlt: 'Allentown PA flood-damaged house near Jordan Creek',
    description: 'Selling a flood-damaged house in Allentown PA? Jordan Creek and Little Lehigh flood zones, PA disclosure law, FEMA lookup, and why cash buyers can simplify the sale.',
    primaryKeyword: 'sell flood damaged house Allentown PA',
    markets: ['allentown-pa'],
    isStatic: true,
  },
  {
    slug: 'sell-house-code-violations-allentown-pa',
    title: "Allentown PA Code Violations: What the City Can — and Can't — Do to Your Sale",
    excerpt: "Allentown requires a Pre-Sale Inspection and Certificate of Compliance before you can sell. Here's how the city's property maintenance process actually works — and where cash buyers fit.",
    date: 'April 30, 2026',
    datePublished: '2026-04-30',
    category: 'Code Violations',
    readTime: '7 min',
    heroImage: '/images/allentown-hero.jpg',
    heroAlt: 'Allentown PA home with code violations — selling options',
    description: "Selling a house with code violations in Allentown PA? Learn how the city's Pre-Sale Inspection, Certificate of Compliance, and buyer acceptance process actually work — and where cash buyers fit.",
    primaryKeyword: 'sell house code violations Allentown PA',
    markets: ['allentown-pa'],
    isStatic: true,
  },
  {
    slug: 'allentown-pa-cash-buyers-by-neighborhood',
    title: 'Where Allentown Cash Buyers Are Most Active — A Neighborhood-by-Neighborhood Breakdown',
    excerpt: "Not every Allentown neighborhood works the same for sellers. Here's where cash buyers concentrate their activity — East Allentown, Center City, Jordan Heights, West End, and more — with current data and honest caveats.",
    date: 'April 30, 2026',
    datePublished: '2026-04-30',
    category: 'Market Guide',
    readTime: '8 min',
    heroImage: '/images/allentown-hero.jpg',
    heroAlt: 'Allentown PA neighborhoods — cash buyer activity',
    description: 'Which Allentown neighborhoods see the most cash buyer activity in 2026? East Allentown, Center City, Jordan Heights, West End, and more — with current data and honest caveats.',
    primaryKeyword: 'sell house fast Allentown PA neighborhood',
    markets: ['allentown-pa'],
    isStatic: true,
  },
];

/** Get all posts sorted by date (newest first) */
export function getAllPosts(): BlogPostMeta[] {
  return [...BLOG_POSTS].sort(
    (a, b) => new Date(b.datePublished).getTime() - new Date(a.datePublished).getTime()
  );
}

/** Get a single post by slug */
export function getPostMeta(slug: string): BlogPostMeta | undefined {
  return BLOG_POSTS.find((p) => p.slug === slug);
}

/** Get posts that support a specific market page's internal-link cluster */
export function getPostsForMarket(marketSlug: string): BlogPostMeta[] {
  return getAllPosts().filter((post) => post.markets.includes(marketSlug));
}

/** Get slugs for dynamic posts only (used for generateStaticParams) */
export function getDynamicPostSlugs(): string[] {
  return BLOG_POSTS.filter((p) => !p.isStatic).map((p) => p.slug);
}
